/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "error": {
        "common": {
            "abnormal_request": string;
            "demo_env_forbidden": string;
        };
        "auth": {
            "no_operational_permissions": string;
            "invalid_token": string;
        };
        "user": {
            "username_cannot_be_empty": string;
            "password_cannot_be_empty": string;
            "user_not_exist": string;
            "username_or_password_incorrect": string;
        };
        "role": {
            "role_name_exist": string;
            "role_in_use": string;
            "role_not_exist": string;
        };
        "profile": {
            "old_password_incorrect": string;
        };
        "verify": {
            "field": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
